INSERT INTO station (name) VALUES
    ('DARTFORD'),
    ('DARTMOUTH'),
    ('TOWER HILL'),
    ('DERBY'),
    ('LIVERPOOL'),
    ('LIVERPOOL LIME STREET'),
    ('PADDINGTON'),
    ('EUSTON'),
    ('LONDON BRIDGE'),
    ('VICTORIA'),
    ('Aalst railway station'),
    ('Aalter railway station'),
    ('Aarschot railway station'),
    ('Alken (B) railway station'),
    ('Ans railway station'),
    ('Antwerpen-Berchem railway station'),
    ('Antwerpen-Centraal railway station'),
    ('Antwerpen-Luchtbal railway station'),
    ('Antwerpen-Noorderdokken railway station'),
    ('Antwerpen-Zuid railway station'),
    ('Haacht railway station'),
    ('Halle (B) railway station'),
    ('Harelbeke railway station'),
    ('Hasselt railway station'),
    ('Heide (B) railway station'),
    ('Heist railway station'),
    ('Heist-op-den-Berg railway station'),
    ('Herbesthal railway station'),
    ('Herentals railway station'),
    ('Hove (B) railway station'),
    ('Kalmthout railway station'),
    ('Kapellen (B) railway station'),
    ('Kessel railway station'),
    ('Kiewit railway station'),
    ('Kijkuit railway station'),
    ('Knokke railway station'),
    ('Kontich-Lint railway station'),
    ('Kortrijk railway station'),
    ('Beveren railway station'),
    ('Blankenberge railway station'),
    ('Boechout railway station'),
    ('Bokrijk railway station'),
    ('Bouwel railway station'),
    ('Braine-le-Comte railway station'),
    ('Brugge railway station'),
    ('Waarschoot railway station'),
    ('Waterloo (B) railway station'),
    ('Weerde railway station'),
    ('Welkenraedt railway station'),
    ('Wildert railway station'),
    ('Wolfstee railway station');